#ifndef OPTIONS_H
#define OPTIONS_H

#include "files.h"
#include "defines.h"
#include "types.h"

namespace bnc {

extern filename_t files;

void init_options();

extern int OPT_LOOKAHEAD;
extern int OPT_TIME_LIMIT;
extern int OPT_RESERVE;
extern int OPT_ORDER;
extern bdd_t OPT_BDD_TYPE;
extern compilation_t OPT_COMPILATION_TYPE;
extern bool
    OPT_USE_PROBABILITY,
    OPT_DETERMINISM,
    OPT_ENCODE_STRUCTURE,
    OPT_PARTITION,
    OPT_READ_PARTITION,
    OPT_READ_PSEUDO_ORDERING,
    OPT_READ_ORDERING,
    OPT_READ_VARIABLE_ORDERING,
    OPT_READ_ELIM_ORDERING,
    OPT_SA_READ_ELIM_ORDERING,
    OPT_WRITE_BINARY,
    OPT_WRITE_PARTITION,
    OPT_WRITE_STATS,
    OPT_WRITE_ORDERING,
    OPT_WRITE_PSEUDO_ORDERING,
    OPT_WRITE_ELIM_ORDERING,
    OPT_WRITE_VARIABLE_ORDERING,
    OPT_WRITE_COMPOSITION_ORDERING,
    OPT_WRITE_DOT,
    OPT_WRITE_SPANNING,
    OPT_WRITE_UAI,
    OPT_WRITE_PS,
    OPT_WRITE_CNF,
    OPT_WRITE_AC,
    OPT_WRITE_MAPPING,
    OPT_ORDER_POST_WEIGHT,
    OPT_NODE_LEVEL_COMPILATION,
    OPT_COLLAPSE,
    OPT_INFO,
    OPT_SA_PARALLELISM,
    OPT_PARALLELISM,
    OPT_PARALLEL_CONJOIN,
    OPT_PARALLEL_CUBE,
    OPT_PARALLEL_PARTITION,
    OPT_TOPDOWN_COMPILATION,
    OPT_NO_COMPILE,
    OPT_NO_ORDERING,
    OPT_SHOW_SCORE,
    OPT_SA_PRINT_ORDERING,
    OPT_BEST_COMPOSITION_ORDERING;

extern unsigned int OPT_PARALLEL_LEVEL;
extern int OPT_PARALLEL_CPT;
extern float OPT_COMPUTED_TABLE_LOAD_FACTOR;
extern size_t OPT_COMPUTED_TABLE_BUCKETS;
extern int OPT_NR_PARTITIONS;
extern unsigned int OPT_WORKERS;
extern int OPT_SA_ITERATIONS;
extern unsigned int OPT_SA_RUNS;
extern double OPT_SA_TEMPERATURE_INITIAL;
extern double OPT_SA_TEMPERATURE_MIN;
extern double OPT_SA_TEMPERATURE_DAMP_FACTOR;
extern double OPT_SA_SCORE_RATIO;
extern int OPT_SA_TRIES;
}

#endif
